# schools_data.py
# Coordinates are hardcoded to avoid geocoding delays and rate limits.
# Only includes schools that offer förskoleklass (grade F).

SCHOOLS = {

    # ─── KOMMUNALA SKOLOR ───────────────────────────────────

    "backaskolan": {
        "name": "Backaskolan",
        "type": "kommunal",
        "spots": 30,
        "demand": "medium",
        "address": "Kulgränden 23, Lund, Sweden",
        "area": "Norra Fäladen",
        "coords": (55.7198, 13.1772),
    },
    "byskolan": {
        "name": "Byskolan",
        "type": "kommunal",
        "spots": 20,
        "demand": "low",
        "address": "Byvägen 7, Södra Sandby, Sweden",
        "area": "Södra Sandby",
        "coords": (55.7167, 13.3333),
    },
    "delfinskolan": {
        "name": "Delfinskolan",
        "type": "kommunal",
        "spots": 25,
        "demand": "medium",
        "address": "Kämnärsvägen 62, Lund, Sweden",
        "area": "Norra Fäladen",
        "coords": (55.7221, 13.1756),
    },
    "flygelskolan": {
        "name": "Flygelskolan",
        "type": "kommunal",
        "spots": 25,
        "demand": "medium",
        "address": "Musikantvägen 3, Lund, Sweden",
        "area": "Östra torn",
        "coords": (55.7089, 13.2189),
    },
    "fagelskolan": {
        "name": "Fågelskolan",
        "type": "kommunal",
        "spots": 30,
        "demand": "medium",
        "address": "Gässlingavägen 21, Lund, Sweden",
        "area": "Papegojelyckan",
        "coords": (55.7156, 13.1578),
    },
    "gunnesboskolan": {
        "name": "Gunnesboskolan",
        "type": "kommunal",
        "spots": 25,
        "demand": "high",
        "address": "Stenåldersvägen 6, Lund, Sweden",
        "area": "Gunnesbo",
        "coords": (55.7301, 13.1667),
    },
    "hubertusgarden": {
        "name": "Hubertusgården",
        "type": "kommunal",
        "spots": 25,
        "demand": "medium",
        "address": "Spårsnögatan 66, Lund, Sweden",
        "area": "Nöbbelöv",
        "coords": (55.7089, 13.1578),
    },
    "klostergardsskolan": {
        "name": "Klostergårdsskolan",
        "type": "kommunal",
        "spots": 25,
        "demand": "medium",
        "address": "Nordanväg 13, Lund, Sweden",
        "area": "Klostergården",
        "coords": (55.6978, 13.1867),
    },
    "kulparkskolan": {
        "name": "Kulparkskolan",
        "type": "kommunal",
        "spots": 20,
        "demand": "low",
        "address": "Kavallerivägen 1, Lund, Sweden",
        "area": "Stångby",
        "coords": (55.7456, 13.1489),
    },
    "lerbäckskolan": {
        "name": "Lerbäckskolan",
        "type": "kommunal",
        "spots": 30,
        "demand": "medium",
        "address": "Öresundsvägen 2, Lund, Sweden",
        "area": "Kobjer",
        "coords": (55.6889, 13.2089),
    },
    "martenskolan": {
        "name": "Mårtenskolan",
        "type": "kommunal",
        "spots": 25,
        "demand": "medium",
        "address": "Gåsatoften 1, Lund, Sweden",
        "area": "Tuna",
        "coords": (55.7156, 13.2067),
    },
    "munspelet": {
        "name": "Munspelets skola",
        "type": "kommunal",
        "spots": 25,
        "demand": "medium",
        "address": "Musikantvägen 5, Lund, Sweden",
        "area": "Östra torn",
        "coords": (55.7092, 13.2195),
    },
    "oskarskolan": {
        "name": "Oskarskolan",
        "type": "kommunal",
        "spots": 20,
        "demand": "medium",
        "address": "Svenska Vägen 10B, Lund, Sweden",
        "area": "Nöbbelöv",
        "coords": (55.7067, 13.1612),
    },
    "palettskolan": {
        "name": "Palettskolan",
        "type": "kommunal",
        "spots": 25,
        "demand": "medium",
        "address": "Rådmansvångsvägen 1, Lund, Sweden",
        "area": "Rådmansvången",
        "coords": (55.6978, 13.1978),
    },
    "tunaskolan": {
        "name": "Tunaskolan",
        "type": "kommunal",
        "spots": 50,
        "demand": "medium",
        "address": "Warholms väg 10, Lund, Sweden",
        "area": "Tuna",
        "coords": (55.7134, 13.2089),
    },
    "vallkarra": {
        "name": "Vallkärra skola",
        "type": "kommunal",
        "spots": 20,
        "demand": "low",
        "address": "Kävlingevägen 103, Lund, Sweden",
        "area": "Vallkärra",
        "coords": (55.7389, 13.1267),
    },
    "vegalyckan": {
        "name": "Vegalyckan",
        "type": "kommunal",
        "spots": 25,
        "demand": "medium",
        "address": "Råbyvägen 19, Lund, Sweden",
        "area": "Stampelyckan",
        "coords": (55.7001, 13.2134),
    },
    "vikingaskolan": {
        "name": "Vikingaskolan",
        "type": "kommunal",
        "spots": 30,
        "demand": "medium",
        "address": "Egils Gränd 16, Lund, Sweden",
        "area": "Linero",
        "coords": (55.7023, 13.2378),
    },
    "varfruskolan": {
        "name": "Vårfruskolan",
        "type": "kommunal",
        "spots": 25,
        "demand": "high",
        "address": "Råbygatan 8, Lund, Sweden",
        "area": "Stadskärnan",
        "coords": (55.7001, 13.1867),
    },

    # ─── FRISTÅENDE MONTESSORI ──────────────────────────────

    "lmg": {
        "name": "Lunds Montessorigrundskola (LMG)",
        "type": "montessori",
        "spots": 20,
        "demand": "high",
        "address": "Sankt Lars väg 40, Lund, Sweden",
        "area": "S:t Larsparken",
        "coords": (55.7112, 13.2012),
    },
    "mondial": {
        "name": "Montessori Mondial Lund",
        "type": "montessori",
        "spots": 20,
        "demand": "high",
        "address": "Landgillevägen 39, Lund, Sweden",
        "area": "Linero",
        "coords": (55.7034, 13.2356),
    },
    "bmsl": {
        "name": "Bilingual Montessori School of Lund (BMSL)",
        "type": "montessori",
        "spots": 20,
        "demand": "high",
        "address": "Margaretavägen 1, Lund, Sweden",
        "area": "Möllevången",
        "coords": (55.7056, 13.1923),
    },
}

NO_FORSKOLEKLASS = {
    "ies": {
        "name": "Internationella Engelska Skolan Lund",
        "note": "Börjar på åk 4 — ingen förskoleklass",
        "address": "Sankt Lars väg 90, Lund, Sweden",
    },
    "kunskapsskolan": {
        "name": "Kunskapsskolan Lund",
        "note": "Börjar på åk 4 — ingen förskoleklass",
        "address": "S:t Lars väg 19, Lund, Sweden",
    },
}